Repository Eukalyptus-Dreizack/deepcity-framework, pull requests merged in 2019-10, with the labels that each got.

#6 Add gitignore and editorconfig
  .editorconfig
  .gitattributes
  .gitignore
Labels: enhancement

#9 Add basic package definition for dependency management
  package.json
  pnpm-lock.yaml
Labels: enhancement

#10 Add code owners
  .github/CODEOWNERS
Labels: enhancement

#12 Create license file
  LICENSE
Labels: documentation

#15 Create the code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#20 Add contributing guidelines
  CONTRIBUTING.md
Labels: C9 - documentation

#16 Feature/readme - added little content in readme
  .github/MEDIA/logo.png
  README.MD
  README.md
  package.json
Labels: C9 - documentation, S2 - in progress

#27 Change Travis Ci badge design
  README.md
Labels: C4 - documentation, S6 - in progress

#23 Update issue templates
  .github/ISSUE_TEMPLATE/a-question.md
  .github/ISSUE_TEMPLATE/a-request-for-a-new-feature.md
  .github/ISSUE_TEMPLATE/an-improvement-of-an-existing-feature.md
  .github/ISSUE_TEMPLATE/bug-report--critical-.md
  .github/ISSUE_TEMPLATE/bug-report--medium-.md
  .github/ISSUE_TEMPLATE/bug-report--normal-.md
  .github/ISSUE_TEMPLATE/improvements-or-additions-to-documentation.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  README.md
Labels: C4 - documentation, S6 - in progress

#31 Fixed not working PR template
  .github/pull_request_template.md
Labels: C4 - documentation

#30 Add gulp and a clean task
  .gitignore
  gulpfile.js
  package.json
  pnpm-lock.yaml
  tasks/gulp-tasks/misc/task-clean.js
  tasks/tasks.js
Labels: C3 - enhancement

#32 Add tsconfig and gulp tasks
  .gitignore
  package.json
  pnpm-lock.yaml
  src/server.ts
  tasks/gulp-tasks/compile/transpile-ts.js
  tasks/tasks.js
  tsconfig.json
Labels: C3 - enhancement

#37 Replaced getting started with wiki links
  README.md
Labels: C4 - documentation

#34 Add ESLint checks
  .eslintrc.js
  package.json
  pnpm-lock.yaml
  src/server.ts
  tasks/gulp-tasks/qa/lint-ts.js
  tasks/tasks.js
Labels: C3 - enhancement

#38 Add Jest and TravisCI
  .eslintignore
  .eslintrc.js
  .travis.yml
  jest.config.js
  package.json
  pnpm-lock.yaml
  src/server.ts
  src/test/server.spec.ts
  tasks/gulp-tasks/qa/jest-coverage.js
  tasks/gulp-tasks/qa/jest-test.js
  tasks/tasks.js
  tsconfig.eslint.json
  tsconfig.json
Labels: C3 - enhancement

#44 Add lock files to .gitignore
  .gitignore
Labels: C3 - enhancement

#41 Update engines
  .travis.yml
  package.json
Labels: C3 - enhancement
